version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CMS_GRAPHQL_URL: ${NEXT_PUBLIC_CMS_GRAPHQL_URL:-http://localhost:4000/graphql}
        NEXT_PUBLIC_UPLOAD_URL: ${NEXT_PUBLIC_UPLOAD_URL:-http://localhost:4000/upload}
        NEXT_PUBLIC_MAINTENANCE_MODE: ${NEXT_PUBLIC_MAINTENANCE_MODE:-false}
        NEXT_PUBLIC_YANDEX_MAPS_API_KEY: ${NEXT_PUBLIC_YANDEX_MAPS_API_KEY}
        PARTSAPI_URL: ${PARTSAPI_URL:-https://api.parts-index.com}
        FRONTEND_PORT: ${FRONTEND_PORT:-3000}
        NODE_ENV: ${NODE_ENV:-production}
    container_name: protekauto-frontend
    ports:
      - "3001:3000"
    environment:
      # Порт приложения
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      
      # Окружение
      - NODE_ENV=${NODE_ENV:-production}
      
      # API конфигурация
      - NEXT_PUBLIC_CMS_GRAPHQL_URL=${NEXT_PUBLIC_CMS_GRAPHQL_URL:-http://localhost:4000/graphql}
      - NEXT_PUBLIC_UPLOAD_URL=${NEXT_PUBLIC_UPLOAD_URL:-http://localhost:4000/upload}
      - NEXT_PUBLIC_MAINTENANCE_MODE=${NEXT_PUBLIC_MAINTENANCE_MODE:-false}
      - PARTSAPI_URL=${PARTSAPI_URL:-https://api.parts-index.com}
        
      # Yandex Maps API
      - NEXT_PUBLIC_YANDEX_MAPS_API_KEY=${NEXT_PUBLIC_YANDEX_MAPS_API_KEY}
      
    restart: unless-stopped
    networks:
      - protekauto-network

networks:
  protekauto-network:
    driver: bridge 